# Generated by Django 4.2 on 2023-04-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_at_origin', models.CharField()),
                ('type', models.CharField()),
                ('created_at', models.DateTimeField(verbose_name='Date created')),
                ('object', models.CharField()),
                ('customer_id', models.CharField()),
                ('payment_url', models.CharField()),
            ],
        ),
    ]
